spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://lams-lbn.com:3306/test
    username: Lamsadmin
    password: Lamsadmin!
    hikari:
      idle-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: none
      temp:
        use_jdbc_metadata_defaults: false
    show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.HSQLDialect
logging:
  pattern:
    console: "%d{HH:mm:ss} %highlight(%-5level) %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%-5level] %logger{36} - %msg%n"
  level:
    root: INFO
    org.hibernate: ERROR