spring:
  datasource:
    url: jdbc:sqlite:./db
    driverClassName: org.sqlite.JDBC
    user: ""
    password: ""
    hikari:
      idle-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: none
      temp:
        use_jdbc_metadata_defaults: false
    show-sql: true
    database-platform: com.enigmabridge.hibernate.dialect.SQLiteDialect
  properties:
    hibernate:
      dialect: com.enigmabridge.hibernate.dialect.SQLiteDialect
logging:
  pattern:
    console: "%d{HH:mm:ss} %highlight(%-5level) %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%-5level] %logger{36} - %msg%n"
  level:
    root: INFO
    org.hibernate: ERROR